---
deployment:
  tasks:
    # Next line defines a DEPLOYPATH with the path to the document root of your website so that you will not have to enter it in each command manually:
    - export DEPLOYPATH=/home/purviagr/
    #copy all from the root (note that this command will not copy hidden files or folders located in the root folder, such as ".git" or ".htaccess"):
    - cp -r * $DEPLOYPATH
